
package com.neptune.webservice.odp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ExchangeODPServiceSoap", targetNamespace = "http://52.10.194.92/neptune/sync/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExchangeODPServiceSoap {


    /**
     * This Method store customer ODP in webserver
     * 
     * @param odp
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetODPBackUp", action = "http://52.10.194.92/neptune/sync/SetODPBackUp")
    @WebResult(name = "SetODPBackUpResult", targetNamespace = "http://52.10.194.92/neptune/sync/")
    @RequestWrapper(localName = "SetODPBackUp", targetNamespace = "http://52.10.194.92/neptune/sync/", className = "_92._194._10._52.neptune.sync.SetODPBackUp")
    @ResponseWrapper(localName = "SetODPBackUpResponse", targetNamespace = "http://52.10.194.92/neptune/sync/", className = "_92._194._10._52.neptune.sync.SetODPBackUpResponse")
    public String setODPBackUp(
        @WebParam(name = "_odp", targetNamespace = "http://52.10.194.92/neptune/sync/")
        ODP odp);

    /**
     * This Method return customer stored ODP from webserver
     * 
     * @param odp
     * @return
     *     returns _92._194._10._52.neptune.sync.ODP
     */
    @WebMethod(operationName = "GetODPBackUp", action = "http://52.10.194.92/neptune/sync/GetODPBackUp")
    @WebResult(name = "GetODPBackUpResult", targetNamespace = "http://52.10.194.92/neptune/sync/")
    @RequestWrapper(localName = "GetODPBackUp", targetNamespace = "http://52.10.194.92/neptune/sync/", className = "_92._194._10._52.neptune.sync.GetODPBackUp")
    @ResponseWrapper(localName = "GetODPBackUpResponse", targetNamespace = "http://52.10.194.92/neptune/sync/", className = "_92._194._10._52.neptune.sync.GetODPBackUpResponse")
    public ODP getODPBackUp(
        @WebParam(name = "_odp", targetNamespace = "http://52.10.194.92/neptune/sync/")
        ODP odp);

}
