
package com.neptune.webservice.odp;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ExchangeODPService", targetNamespace = "http://52.10.194.92/neptune/sync/", wsdlLocation = "http://52.10.194.92/neptune/sync/ExchangeODPService.asmx?wsdl")
public class ExchangeODPService
    extends Service
{

    private final static URL EXCHANGEODPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.neptune.webservice.odp.ExchangeODPService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.neptune.webservice.odp.ExchangeODPService.class.getResource(".");
            url = new URL(baseUrl, "http://52.10.194.92/neptune/sync/ExchangeODPService.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://52.10.194.92/neptune/sync/ExchangeODPService.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EXCHANGEODPSERVICE_WSDL_LOCATION = url;
    }

    public ExchangeODPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExchangeODPService() {
        super(EXCHANGEODPSERVICE_WSDL_LOCATION, new QName("http://52.10.194.92/neptune/sync/", "ExchangeODPService"));
    }

    /**
     * 
     * @return
     *     returns ExchangeODPServiceSoap
     */
    @WebEndpoint(name = "ExchangeODPServiceSoap")
    public ExchangeODPServiceSoap getExchangeODPServiceSoap() {
        return super.getPort(new QName("http://52.10.194.92/neptune/sync/", "ExchangeODPServiceSoap"), ExchangeODPServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExchangeODPServiceSoap
     */
    @WebEndpoint(name = "ExchangeODPServiceSoap")
    public ExchangeODPServiceSoap getExchangeODPServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://52.10.194.92/neptune/sync/", "ExchangeODPServiceSoap"), ExchangeODPServiceSoap.class, features);
    }

}
