//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 09:43:20 PM IST 
//
package com.neptune.schema;

import com.neptune.util.DateUtil;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="channels">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="station" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="schedule">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="campaign" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="track" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;simpleContent>
 *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                                         &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                                                         &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="artist" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}time" />
 *                                                       &lt;/extension>
 *                                                     &lt;/simpleContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="repeat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="timerepeat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="playorder" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="programme" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="playlist">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="track" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;simpleContent>
 *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                                         &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                                                         &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="genre" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                                                         &lt;attribute name="artist" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}time" />
 *                                                         &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}time" />
 *                                                         &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}time" />
 *                                                         &lt;attribute name="synced" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                       &lt;/extension>
 *                                                     &lt;/simpleContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="endtimerule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="repeat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Device" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="User" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SyncNow" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "channels"
})
@XmlRootElement(name = "media")
public class Media {

    @XmlElement(required = true)
    protected Media.Channels channels;
    @XmlAttribute(name = "Device")
    protected String device;
    @XmlAttribute(name = "User")
    protected String user;
    @XmlAttribute(name = "SyncNow")
    protected Byte syncNow;

    /**
     * Gets the value of the channels property.
     *
     * @return possible object is {@link Media.Channels }
     *
     */
    public Media.Channels getChannels() {
        return channels;
    }

    /**
     * Sets the value of the channels property.
     *
     * @param value allowed object is {@link Media.Channels }
     *
     */
    public void setChannels(Media.Channels value) {
        this.channels = value;
    }

    /**
     * Gets the value of the device property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDevice(String value) {
        this.device = value;
    }

    /**
     * Gets the value of the user property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the syncNow property.
     *
     * @return possible object is {@link Byte }
     *
     */
    public Byte getSyncNow() {
        return syncNow;
    }

    /**
     * Sets the value of the syncNow property.
     *
     * @param value allowed object is {@link Byte }
     *
     */
    public void setSyncNow(Byte value) {
        this.syncNow = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="station" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="schedule">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="campaign" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="track" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;simpleContent>
     *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="artist" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}time" />
     *                                             &lt;/extension>
     *                                           &lt;/simpleContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="repeat" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="timerepeat" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="playorder" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="programme" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="playlist">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="track" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;simpleContent>
     *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="genre" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                                               &lt;attribute name="artist" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}time" />
     *                                               &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}time" />
     *                                               &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}time" />
     *                                               &lt;attribute name="synced" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                             &lt;/extension>
     *                                           &lt;/simpleContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="endtimerule" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="repeat" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "station"
    })
    public static class Channels {

        protected List<Media.Channels.Station> station;

        /**
         * Gets the value of the station property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the station property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStation().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Media.Channels.Station }
         *
         *
         */
        public List<Media.Channels.Station> getStation() {
            if (station == null) {
                station = new ArrayList<Media.Channels.Station>();
            }
            return this.station;
        }

        public void setStation(List<Station> station) {
            this.station = station;
        }
        
        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="schedule">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="campaign" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="track" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;simpleContent>
         *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
         *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="artist" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}time" />
         *                                   &lt;/extension>
         *                                 &lt;/simpleContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="repeat" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="timerepeat" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="playorder" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="programme" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="playlist">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="track" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;simpleContent>
         *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
         *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="genre" type="{http://www.w3.org/2001/XMLSchema}short" />
         *                                     &lt;attribute name="artist" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}time" />
         *                                     &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}time" />
         *                                     &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}time" />
         *                                     &lt;attribute name="synced" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                   &lt;/extension>
         *                                 &lt;/simpleContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="endtimerule" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="repeat" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "schedule",
            "programme"
        })
        public static class Station {

            @XmlElement(required = true)
            protected Media.Channels.Station.Schedule schedule;
            protected List<Media.Channels.Station.Programme> programme;
            @XmlAttribute
            protected Byte id;
            @XmlAttribute
            protected String name;

            /**
             * Gets the value of the schedule property.
             *
             * @return possible object is
             *     {@link Media.Channels.Station.Schedule }
             *
             */
            public Media.Channels.Station.Schedule getSchedule() {
                return schedule;
            }

            
            /**
             * Sets the value of the schedule property.
             *
             * @param value allowed object is
             *     {@link Media.Channels.Station.Schedule }
             *
             */
            public void setSchedule(Media.Channels.Station.Schedule value) {
                this.schedule = value;
            }

            /**
             * Gets the value of the programme property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a <CODE>set</CODE> method for the programme property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getProgramme().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Media.Channels.Station.Programme }
             *
             *
             */
            public List<Media.Channels.Station.Programme> getProgramme() {
                if (programme == null) {
                    programme = new ArrayList<Media.Channels.Station.Programme>();
                }
                return this.programme;
            }

            public void setProgramme(List<Programme> programme) {
                this.programme = programme;
            }

            
            /**
             * Gets the value of the id property.
             *
             * @return possible object is {@link Byte }
             *
             */
            public Byte getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value allowed object is {@link Byte }
             *
             */
            public void setId(Byte value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             *
             * <p>
             * The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="playlist">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="track" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;simpleContent>
             *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
             *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="genre" type="{http://www.w3.org/2001/XMLSchema}short" />
             *                           &lt;attribute name="artist" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}time" />
             *                           &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}time" />
             *                           &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}time" />
             *                           &lt;attribute name="synced" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                         &lt;/extension>
             *                       &lt;/simpleContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="endtimerule" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="repeat" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "playlist"
            })
            public static class Programme {

                @XmlElement(required = true)
                protected Media.Channels.Station.Programme.Playlist playlist;
                @XmlAttribute
                protected Byte id;
                @XmlAttribute
                protected String name;
                @XmlAttribute
                protected String endtimerule;
                @XmlAttribute
                protected String starttime;
                @XmlAttribute
                protected String repeat;
                @XmlAttribute
                protected String shuffle;
                @XmlAttribute
                protected String endtime;

                /**
                 * Gets the value of the playlist property.
                 *
                 * @return possible object is
                 *     {@link Media.Channels.Station.Programme.Playlist }
                 *
                 */
                public Media.Channels.Station.Programme.Playlist getPlaylist() {
                    return playlist;
                }

                /**
                 * Sets the value of the playlist property.
                 *
                 * @param value allowed object is
                 *     {@link Media.Channels.Station.Programme.Playlist }
                 *
                 */
                public void setPlaylist(Media.Channels.Station.Programme.Playlist value) {
                    this.playlist = value;
                }

                /**
                 * Gets the value of the id property.
                 *
                 * @return possible object is {@link Byte }
                 *
                 */
                public Byte getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 *
                 * @param value allowed object is {@link Byte }
                 *
                 */
                public void setId(Byte value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the name property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the endtimerule property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getEndtimerule() {
                    return endtimerule;
                }

                /**
                 * Sets the value of the endtimerule property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setEndtimerule(String value) {
                    this.endtimerule = value;
                }

                /**
                 * Gets the value of the starttime property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getStarttime() {
                    return starttime;
                }

                /**
                 * Sets the value of the starttime property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setStarttime(String value) {
                    this.starttime = value;
                }

                /**
                 * Gets the value of the repeat property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getRepeat() {
                    return repeat;
                }

                /**
                 * Sets the value of the repeat property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setRepeat(String value) {
                    this.repeat = value;
                }

                public String getShuffle() {
                    return shuffle;
                }

                public void setShuffle(String shuffle) {
                    this.shuffle = shuffle;
                }

                /**
                 * Gets the value of the endtime property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getEndtime() {
                    return endtime;
                }

                /**
                 * Sets the value of the endtime property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setEndtime(String value) {
                    this.endtime = value;
                }

                /**
                 * <p>
                 * Java class for anonymous complex type.
                 *
                 * <p>
                 * The following schema fragment specifies the expected content
                 * contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="track" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;simpleContent>
                 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
                 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="genre" type="{http://www.w3.org/2001/XMLSchema}short" />
                 *                 &lt;attribute name="artist" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}time" />
                 *                 &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}time" />
                 *                 &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}time" />
                 *                 &lt;attribute name="synced" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *               &lt;/extension>
                 *             &lt;/simpleContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "track"
                })
                public static class Playlist {

                    protected List<Media.Channels.Station.Programme.Playlist.Track> track;
                    @XmlAttribute
                    protected String id;

                    /**
                     * Gets the value of the track property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live
                     * list, not a snapshot. Therefore any modification you make
                     * to the returned list will be present inside the JAXB
                     * object. This is why there is not a <CODE>set</CODE>
                     * method for the track property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getTrack().add(newItem);
                     * </pre>
                     *
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Media.Channels.Station.Programme.Playlist.Track }
                     *
                     *
                     */
                    public List<Media.Channels.Station.Programme.Playlist.Track> getTrack() {
                        if (track == null) {
                            track = new ArrayList<Media.Channels.Station.Programme.Playlist.Track>();
                        }
                        return this.track;
                    }

                    /**
                     * Gets the value of the id property.
                     *
                     * @return possible object is {@link String }
                     *
                     */
                    public String getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     *
                     * @param value allowed object is {@link String }
                     *
                     */
                    public void setId(String value) {
                        this.id = value;
                    }

                    public void setTrack(List<Track> track) {
                        this.track = track;
                    }

                    /**
                     * <p>
                     * Java class for anonymous complex type.
                     *
                     * <p>
                     * The following schema fragment specifies the expected
                     * content contained within this class.
                     *
                     * <pre>
                     * &lt;complexType>
                     *   &lt;simpleContent>
                     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
                     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="genre" type="{http://www.w3.org/2001/XMLSchema}short" />
                     *       &lt;attribute name="artist" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}time" />
                     *       &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}time" />
                     *       &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}time" />
                     *       &lt;attribute name="synced" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *     &lt;/extension>
                     *   &lt;/simpleContent>
                     * &lt;/complexType>
                     * </pre>
                     *
                     *
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Track implements Comparable {

                        @XmlValue
                        protected String value;
                        @XmlAttribute
                        protected Long id;
                        @XmlAttribute
                        protected String name;
                        @XmlAttribute
                        protected String ondemandlabel;
                        @XmlAttribute
                        protected Short genre;
                        @XmlAttribute
                        protected String artist;
                        @XmlAttribute
                        @XmlSchemaType(name = "time")
                        protected XMLGregorianCalendar length;
                        @XmlAttribute
                        protected String starttime;
                        @XmlAttribute
                        protected String endtime;
                        @XmlAttribute
                        protected String synced;
                        @XmlAttribute
                        protected String title;

                        /**
                         * Gets the value of the value property.
                         *
                         * @return possible object is {@link String }
                         *
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         *
                         * @param value allowed object is {@link String }
                         *
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                        /**
                         * Gets the value of the id property.
                         *
                         * @return possible object is {@link Short }
                         *
                         */
                        public Long getId() {
                            return id;
                        }

                        /**
                         * Sets the value of the id property.
                         *
                         * @param value allowed object is {@link Short }
                         *
                         */
                        public void setId(Long value) {
                            this.id = value;
                        }

                        /**
                         * Gets the value of the name property.
                         *
                         * @return possible object is {@link String }
                         *
                         */
                        public String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         *
                         * @param value allowed object is {@link String }
                         *
                         */
                        public void setName(String value) {
                            this.name = value;
                        }

                        public String getOndemandlabel() {
                            return ondemandlabel;
                        }

                        public void setOndemandlabel(String ondemandlabel) {
                            this.ondemandlabel = ondemandlabel;
                        }

                        /**
                         * Gets the value of the genre property.
                         *
                         * @return possible object is {@link Short }
                         *
                         */
                        public Short getGenre() {
                            return genre;
                        }

                        /**
                         * Sets the value of the genre property.
                         *
                         * @param value allowed object is {@link Short }
                         *
                         */
                        public void setGenre(Short value) {
                            this.genre = value;
                        }

                        /**
                         * Gets the value of the artist property.
                         *
                         * @return possible object is {@link String }
                         *
                         */
                        public String getArtist() {
                            return artist;
                        }

                        /**
                         * Sets the value of the artist property.
                         *
                         * @param value allowed object is {@link String }
                         *
                         */
                        public void setArtist(String value) {
                            this.artist = value;
                        }

                        /**
                         * Gets the value of the length property.
                         *
                         * @return possible object is
                         *     {@link XMLGregorianCalendar }
                         *
                         */
                        public XMLGregorianCalendar getLength() {
                            return length;
                        }

                        /**
                         * Sets the value of the length property.
                         *
                         * @param value allowed object is
                         *     {@link XMLGregorianCalendar }
                         *
                         */
                        public void setLength(XMLGregorianCalendar value) {
                            this.length = value;
                        }

                        /**
                         * Gets the value of the starttime property.
                         *
                         * @return possible object is
                         *     {@link XMLGregorianCalendar }
                         *
                         */
                        public String getStarttime() {
                            return starttime;
                        }

                        /**
                         * Sets the value of the starttime property.
                         *
                         * @param value allowed object is
                         *     {@link XMLGregorianCalendar }
                         *
                         */
                        public void setStarttime(String value) {
                            this.starttime = value;
                        }

                        /**
                         * Gets the value of the endtime property.
                         *
                         * @return possible object is
                         *     {@link XMLGregorianCalendar }
                         *
                         */
                        public String getEndtime() {
                            return endtime;
                        }

                        /**
                         * Sets the value of the endtime property.
                         *
                         * @param value allowed object is
                         *     {@link XMLGregorianCalendar }
                         *
                         */
                        public void setEndtime(String value) {
                            this.endtime = value;
                        }

                        /**
                         * Gets the value of the synced property.
                         *
                         * @return possible object is {@link String }
                         *
                         */
                        public String getSynced() {
                            return synced;
                        }

                        /**
                         * Sets the value of the synced property.
                         *
                         * @param value allowed object is {@link String }
                         *
                         */
                        public void setSynced(String value) {
                            this.synced = value;
                        }

                        public String getTitle() {
                            return title;
                        }

                        public void setTitle(String title) {
                            this.title = title;
                        }

                        @Override
                        public int hashCode() {
                            int hash = 7;
                            hash = 43 * hash + (this.name != null ? this.name.hashCode() : 0);
                            return hash;
                        }

                        @Override
                        public boolean equals(Object obj) {
                            if (obj == null) {
                                return false;
                            }
                            if (getClass() != obj.getClass()) {
                                return false;
                            }
                            final Track other = (Track) obj;
                            if ((this.name == null) ? (other.name != null) : !other.name.equals(this.name)) {
                                return false;
                            }
                            return true;
                        }

                        public int compareTo(Object o) {
                            Track track2 = (Track)o;
                            Date track1StartTime = DateUtil.getInstance().getDate(this.getStarttime(), DateUtil.DATE_FORMAT_HH_MM_SS);
                            Date track2StartTime = DateUtil.getInstance().getDate(track2.getStarttime(), DateUtil.DATE_FORMAT_HH_MM_SS);
                            if (track1StartTime.before(track2StartTime)) {
                                return -1;
                            }
                            if (track1StartTime.after(track2StartTime)) {
                                return 1;
                            }

                            return 0;
                        }
                    }

                }

            }

            /**
             * <p>
             * Java class for anonymous complex type.
             *
             * <p>
             * The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="campaign" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="track" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;simpleContent>
             *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
             *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="artist" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}time" />
             *                         &lt;/extension>
             *                       &lt;/simpleContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="repeat" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="timerepeat" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="playorder" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "campaign"
            })
            public static class Schedule {

                protected List<Media.Channels.Station.Schedule.Campaign> campaign;

                /**
                 * Gets the value of the campaign property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object. This is
                 * why there is not a <CODE>set</CODE> method for the campaign
                 * property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCampaign().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Media.Channels.Station.Schedule.Campaign }
                 *
                 *
                 */
                public List<Media.Channels.Station.Schedule.Campaign> getCampaign() {
                    if (campaign == null) {
                        campaign = new ArrayList<Media.Channels.Station.Schedule.Campaign>();
                    }
                    return this.campaign;
                }

                /**
                 * <p>
                 * Java class for anonymous complex type.
                 *
                 * <p>
                 * The following schema fragment specifies the expected content
                 * contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="track" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;simpleContent>
                 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
                 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="artist" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}time" />
                 *               &lt;/extension>
                 *             &lt;/simpleContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
                 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="repeat" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="timerepeat" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="playorder" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "track"
                })
                public static class Campaign {

                    protected List<Media.Channels.Station.Schedule.Campaign.Track> track;
                    @XmlAttribute
                    protected Byte id;
                    @XmlAttribute
                    protected String name;
                    @XmlAttribute
                    protected String repeat;
                    @XmlAttribute
                    protected String timerepeat;
                    @XmlAttribute
                    protected String playorder;

                    /**
                     * Gets the value of the track property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live
                     * list, not a snapshot. Therefore any modification you make
                     * to the returned list will be present inside the JAXB
                     * object. This is why there is not a <CODE>set</CODE>
                     * method for the track property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getTrack().add(newItem);
                     * </pre>
                     *
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Media.Channels.Station.Schedule.Campaign.Track }
                     *
                     *
                     */
                    public List<Media.Channels.Station.Schedule.Campaign.Track> getTrack() {
                        if (track == null) {
                            track = new ArrayList<Media.Channels.Station.Schedule.Campaign.Track>();
                        }
                        return this.track;
                    }

                    /**
                     * Gets the value of the id property.
                     *
                     * @return possible object is {@link Byte }
                     *
                     */
                    public Byte getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     *
                     * @param value allowed object is {@link Byte }
                     *
                     */
                    public void setId(Byte value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the name property.
                     *
                     * @return possible object is {@link String }
                     *
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     *
                     * @param value allowed object is {@link String }
                     *
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the repeat property.
                     *
                     * @return possible object is {@link String }
                     *
                     */
                    public String getRepeat() {
                        return repeat;
                    }

                    /**
                     * Sets the value of the repeat property.
                     *
                     * @param value allowed object is {@link String }
                     *
                     */
                    public void setRepeat(String value) {
                        this.repeat = value;
                    }

                    /**
                     * Gets the value of the timerepeat property.
                     *
                     * @return possible object is {@link String }
                     *
                     */
                    public String getTimerepeat() {
                        return timerepeat;
                    }

                    /**
                     * Sets the value of the timerepeat property.
                     *
                     * @param value allowed object is {@link String }
                     *
                     */
                    public void setTimerepeat(String value) {
                        this.timerepeat = value;
                    }

                    /**
                     * Gets the value of the playorder property.
                     *
                     * @return possible object is {@link String }
                     *
                     */
                    public String getPlayorder() {
                        return playorder;
                    }

                    /**
                     * Sets the value of the playorder property.
                     *
                     * @param value allowed object is {@link String }
                     *
                     */
                    public void setPlayorder(String value) {
                        this.playorder = value;
                    }

                    /**
                     * <p>
                     * Java class for anonymous complex type.
                     *
                     * <p>
                     * The following schema fragment specifies the expected
                     * content contained within this class.
                     *
                     * <pre>
                     * &lt;complexType>
                     *   &lt;simpleContent>
                     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
                     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="artist" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}time" />
                     *     &lt;/extension>
                     *   &lt;/simpleContent>
                     * &lt;/complexType>
                     * </pre>
                     *
                     *
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Track {

                        @XmlValue
                        protected String value;
                        @XmlAttribute
                        protected Short id;
                        @XmlAttribute
                        protected String name;
                        @XmlAttribute
                        protected String artist;
                        @XmlAttribute
                        @XmlSchemaType(name = "time")
                        protected XMLGregorianCalendar length;

                        /**
                         * Gets the value of the value property.
                         *
                         * @return possible object is {@link String }
                         *
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         *
                         * @param value allowed object is {@link String }
                         *
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                        /**
                         * Gets the value of the id property.
                         *
                         * @return possible object is {@link Short }
                         *
                         */
                        public Short getId() {
                            return id;
                        }

                        /**
                         * Sets the value of the id property.
                         *
                         * @param value allowed object is {@link Short }
                         *
                         */
                        public void setId(Short value) {
                            this.id = value;
                        }

                        /**
                         * Gets the value of the name property.
                         *
                         * @return possible object is {@link String }
                         *
                         */
                        public String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         *
                         * @param value allowed object is {@link String }
                         *
                         */
                        public void setName(String value) {
                            this.name = value;
                        }

                        /**
                         * Gets the value of the artist property.
                         *
                         * @return possible object is {@link String }
                         *
                         */
                        public String getArtist() {
                            return artist;
                        }

                        /**
                         * Sets the value of the artist property.
                         *
                         * @param value allowed object is {@link String }
                         *
                         */
                        public void setArtist(String value) {
                            this.artist = value;
                        }

                        /**
                         * Gets the value of the length property.
                         *
                         * @return possible object is
                         *     {@link XMLGregorianCalendar }
                         *
                         */
                        public XMLGregorianCalendar getLength() {
                            return length;
                        }

                        /**
                         * Sets the value of the length property.
                         *
                         * @param value allowed object is
                         *     {@link XMLGregorianCalendar }
                         *
                         */
                        public void setLength(XMLGregorianCalendar value) {
                            this.length = value;
                        }

                    }

                }

            }

        }

    }

}
