//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 09:43:20 PM IST 
//


package com.neptune.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.neptune.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.neptune.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Media.Channels.Station.Programme.Playlist.Track }
     * 
     */
    public Media.Channels.Station.Programme.Playlist.Track createMediaChannelsStationProgrammePlaylistTrack() {
        return new Media.Channels.Station.Programme.Playlist.Track();
    }

    /**
     * Create an instance of {@link Media.Channels.Station.Schedule }
     * 
     */
    public Media.Channels.Station.Schedule createMediaChannelsStationSchedule() {
        return new Media.Channels.Station.Schedule();
    }

    /**
     * Create an instance of {@link Media.Channels.Station.Programme }
     * 
     */
    public Media.Channels.Station.Programme createMediaChannelsStationProgramme() {
        return new Media.Channels.Station.Programme();
    }

    /**
     * Create an instance of {@link Media.Channels.Station.Schedule.Campaign.Track }
     * 
     */
    public Media.Channels.Station.Schedule.Campaign.Track createMediaChannelsStationScheduleCampaignTrack() {
        return new Media.Channels.Station.Schedule.Campaign.Track();
    }

    /**
     * Create an instance of {@link Media.Channels }
     * 
     */
    public Media.Channels createMediaChannels() {
        return new Media.Channels();
    }

    /**
     * Create an instance of {@link Media.Channels.Station.Schedule.Campaign }
     * 
     */
    public Media.Channels.Station.Schedule.Campaign createMediaChannelsStationScheduleCampaign() {
        return new Media.Channels.Station.Schedule.Campaign();
    }

    /**
     * Create an instance of {@link Media.Channels.Station.Programme.Playlist }
     * 
     */
    public Media.Channels.Station.Programme.Playlist createMediaChannelsStationProgrammePlaylist() {
        return new Media.Channels.Station.Programme.Playlist();
    }

    /**
     * Create an instance of {@link Media.Channels.Station }
     * 
     */
    public Media.Channels.Station createMediaChannelsStation() {
        return new Media.Channels.Station();
    }

    /**
     * Create an instance of {@link Media }
     * 
     */
    public Media createMedia() {
        return new Media();
    }

}
