/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WidgetUtils;

import com.neptune.common.DataHolder;
import com.neptune.common.OdpEditEnum;
import java.awt.Component;
import java.awt.ComponentOrientation;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ragesh.raveendran
 */
public class OdpPanelInEditMode extends javax.swing.JPanel implements TableCellRenderer {

    /**
     * Creates new form OdpPanelInEditMode
     */
    public OdpPanelInEditMode() {
        intiComponentsManually();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void intiComponentsManually() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1.setText("");
        jLabel2.setText("");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jLabel2))
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        JPanel panel = new OdpPanelInEditMode();
        switch (OdpEditEnum.valueOf(DataHolder.odpModeStatus)) {
            case EDIT:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/odpEdit.png")));
                break;
            default:
                jLabel2.setIcon(null);
                break;
        }
        if (isSelected) {
            this.setBackground(new java.awt.Color(153, 204, 255));
            setForeground(table.getSelectionForeground());
            setBackground(table.getSelectionBackground());
        } else {
            setBackground(table.getBackground());
            if (row % 2 == 0) {
                setBackground(new java.awt.Color(192, 192, 192));
                setBackground(new java.awt.Color(192, 192, 192));
            } else {
                setBackground(new java.awt.Color(160, 160, 160));
                setBackground(new java.awt.Color(160, 160, 160));
            }
        }

        if (value != null) {
            if ("".equalsIgnoreCase(value.toString())) {
                jLabel1.setText("");
                jLabel2.setIcon(null);
            } else {
                String song = (String) value;
                jLabel1.setText(song);
            }
        }
        jLabel1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jLabel1.setHorizontalAlignment(SwingConstants.LEFT);
        return this;
    }
}
