/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neptune.controller;

import com.neptune.common.DataHolder;
import com.neptune.player.StreamPlayer;
import com.neptune.schema.Media.Channels.Station;
import com.neptune.util.NeptuneLogger;
import java.awt.Color;
import java.nio.file.FileSystems;
import java.util.logging.Level;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.LineUnavailableException;

/**
 *
 * @author ragesh.raveendran
 */
public class PlayerWidget2 extends javax.swing.JFrame {

    /**
     * Creates new form PlayerWidget
     */
    public PlayerWidget2(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
//        initComponents();
//        playerStatusLabel.setText(DataHolder.currentPlayerStatus);
//        jLabel3.setText("<html><marquee>Search</marquee><html>");
        initComponentsOverride();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        volumeSlider = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(797, 386));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.inactiveCaptionText);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 40, 350, 70);

        version.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        version.setForeground(new java.awt.Color(255, 51, 51));
        version.setText("Version 1.0");
        version.setToolTipText("");
        getContentPane().add(version);
        version.setBounds(50, 110, 60, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        jButton1.setToolTipText("Play OnDemand Station");
        jButton1.setFocusPainted(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButton1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 320, 30, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
        jButton2.setToolTipText("Play Other Stations");
        jButton2.setRequestFocusEnabled(false);
        jButton2.setRolloverEnabled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(730, 320, 30, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Programme : ");
        jLabel3.setName("Programme"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 180, 380, 30);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 160, 0, 0);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Track : ");
        jLabel4.setName("Track"); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 200, 280, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Station : OnDemandStation");
        jLabel6.setName("Station"); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 170, 290, 17);

        jLabel7.setText("Station : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 170, 120, 14);

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 190, 34, 14);

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 210, 34, 14);

        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(730, 0, 30, 30);

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(370, 90, 370, 20);

        volumeSlider.setOpaque(false);
        volumeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSliderStateChanged(evt);
            }
        });
        volumeSlider.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                volumeSliderCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        getContentPane().add(volumeSlider);
        volumeSlider.setBounds(420, 200, 330, 23);

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 40, 40, 14);

        jLabel13.setText("Customer Care - 844-255-0603");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(630, 290, 150, 20);

        jButton3.setIcon(new javax.swing.ImageIcon("D:\\Projects\\NeptunePlayer\\src\\main\\resources\\images\\stop.png")); // NOI18N
        jButton3.setText("PlayButton");
        getContentPane().add(jButton3);
        jButton3.setBounds(110, 290, 30, 30);

        jTable1.setBackground(new java.awt.Color(153, 153, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 150, 280, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 360);

        jToggleButton1.setText("jToggleButton1");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(390, 290, 105, 23);

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Projects\\NeptunePlayer\\src\\main\\resources\\images\\play3.png")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(740, 10, 40, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        NeptuneLogger.getInstance().getLogger().log(Level.INFO, "Other Station...");
        DataHolder.currentStation = null;
        DataHolder.playListScrollPanel.setVisible(false);
        DataHolder.currentTrackPath = null;
        StreamPlayer.stop();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        NeptuneLogger.getInstance().getLogger().log(Level.INFO, "On Demand Station Selected");
        DataHolder.currentStation = new Station();
        StreamPlayer.stop();
        DataHolder.currentStation.setName("OnDemandStation");
        if (DataHolder.onDemandTrackList.size() > 0) {
            javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) DataHolder.playList.getModel();
            for (int i = tableModel.getRowCount() -1 ; i > -1; i--) {
                tableModel.removeRow(i);
            }
//            for (int i = 0; i < DataHolder.onDemandTrackList.size(); i++) {
//                tableModel.addRow(new Object[]{DataHolder.onDemandTrackList.get(i).getName(),
//                    DataHolder.onDemandTrackList.get(i).getLength()});
//            }
            DataHolder.playListScrollPanel.setVisible(true);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
//        playListScrollPanel.setVisible(true);
        System.out.println("hjhjhjd");
    }//GEN-LAST:event_jButton1MouseMoved

    private void volumeSliderCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_volumeSliderCaretPositionChanged
        System.out.println("Changed pos");
        System.out.println(volumeSlider.getValue());
    }//GEN-LAST:event_volumeSliderCaretPositionChanged

    private void volumeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSliderStateChanged
        try {
            Clip clip = AudioSystem.getClip();
            FloatControl gainControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);
            gainControl.setValue(volumeSlider.getValue());
            clip.start();

        } catch (LineUnavailableException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_volumeSliderStateChanged

    private void jButton1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseDragged
        System.out.println("sdsdd");
    }//GEN-LAST:event_jButton1MouseDragged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        StreamPlayer.stop();
        DataHolder.currentTrackPath = DataHolder.archiveFolderPath + FileSystems.getDefault().getSeparator()
                + DataHolder.playList.getModel().getValueAt(DataHolder.playList.getSelectedRow(), 0);
        DataHolder.onDemandOverride = true;
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            NeptuneLogger.getInstance().getLogger().log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            NeptuneLogger.getInstance().getLogger().log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            NeptuneLogger.getInstance().getLogger().log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            NeptuneLogger.getInstance().getLogger().log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlayerWidget2 dialog = new PlayerWidget2(new javax.swing.JFrame(), true);
//                dialog.setModalityType(ModalityType.TOOLKIT_MODAL);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel version;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables

    private void initComponentsOverride() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(780, 355));
        setResizable(false);
//        getContentPane().setLayout(null);
        setDefaultLookAndFeelDecorated(true);
        setUndecorated(true);
        setLocationRelativeTo(null);

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        DataHolder.connectivity.setText("");
        DataHolder.connectivity.setBackground(Color.red);
        DataHolder.connectivity.setOpaque(true);
        getContentPane().add(DataHolder.connectivity);
        DataHolder.connectivity.setBounds(750, 10, 10, 10);

        DataHolder.playerStatusLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        DataHolder.playerStatusLabel.setForeground(java.awt.SystemColor.inactiveCaptionText);
        DataHolder.playerStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(DataHolder.playerStatusLabel);
        DataHolder.playerStatusLabel.setBounds(380, 40, 350, 70);

        DataHolder.onDemandStationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        DataHolder.onDemandStationButton.setFocusPainted(false);
        DataHolder.onDemandStationButton.setToolTipText("Play OnDemand Station");
        DataHolder.onDemandStationButton.setRequestFocusEnabled(false);
        DataHolder.onDemandStationButton.setRolloverEnabled(false);

        DataHolder.onDemandStationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(DataHolder.onDemandStationButton);
        DataHolder.onDemandStationButton.setBounds(20, 320, 30, 30);

        DataHolder.otherStationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
        DataHolder.otherStationButton.setToolTipText("Play Other Stations");
        DataHolder.otherStationButton.setLabel("");
        DataHolder.otherStationButton.setRequestFocusEnabled(false);
        DataHolder.otherStationButton.setRolloverEnabled(false);
        DataHolder.otherStationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(DataHolder.otherStationButton);
        DataHolder.otherStationButton.setBounds(730, 320, 30, 30);

        version = new javax.swing.JLabel();
        version.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        version.setForeground(new java.awt.Color(102, 102, 102));
        version.setText("Version " + getClass().getPackage().getImplementationVersion());
        version.setToolTipText("");
        version.setVisible(true);
        getContentPane().add(version);
        version.setBounds(90, 90, 200, 14);

        jLabel7.setText("Station      ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 170, 150, 17);
        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        DataHolder.stationLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DataHolder.stationLabel.setForeground(new java.awt.Color(51, 51, 51));
        DataHolder.stationLabel.setName("Station"); // NOI18N
        getContentPane().add(DataHolder.stationLabel);
        DataHolder.stationLabel.setBounds(475, 170, 290, 17);

        jLabel8.setText("Programme    ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 182, 150, 30);
        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        DataHolder.programmeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DataHolder.programmeLabel.setForeground(new java.awt.Color(51, 51, 51));
        DataHolder.programmeLabel.setName("Programme"); // NOI18N
        getContentPane().add(DataHolder.programmeLabel);
        DataHolder.programmeLabel.setBounds(475, 182, 380, 30);

        jLabel9.setText("Track             ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 210, 150, 14);
        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        DataHolder.currentTrackLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DataHolder.currentTrackLabel.setForeground(new java.awt.Color(51, 51, 51));
        DataHolder.currentTrackLabel.setName("Track"); // NOI18N
        getContentPane().add(DataHolder.currentTrackLabel);
        DataHolder.currentTrackLabel.setBounds(475, 200, 275, 30);

        
        jLabel11.setText("Next Track        ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(380, 228, 150, 14);
        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        DataHolder.nextTrackLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DataHolder.nextTrackLabel.setForeground(new java.awt.Color(51, 51, 51));
        DataHolder.nextTrackLabel.setName("Track");
        getContentPane().add(DataHolder.nextTrackLabel);
        DataHolder.nextTrackLabel.setBounds(475, 218, 275, 30);

        DataHolder.playList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });

        getContentPane().add(DataHolder.playListScrollPanel);
        DataHolder.playListScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        DataHolder.playListScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
//        DataHolder.playListScrollPanel.setCursor();
        DataHolder.playListScrollPanel.setBounds(30, 125, 300, 135);

        DataHolder.downloadFileDetails.setText("");
        getContentPane().add(DataHolder.downloadFileDetails);
        DataHolder.downloadFileDetails.setBounds(380, 90, 370, 20);

        DataHolder.jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        getContentPane().add(DataHolder.jLabel1);
        DataHolder.jLabel1.setBounds(0, 0, 790, 357);

        pack();
    }
}
